# -*- coding: utf-8 -*-
"""calculate_agreement_speaking potatoes

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zOaUxXX4ihKOaTr0TEuXnkm6GSQltApC
"""

import pandas as pd
df = pd.read_csv('/content/speaking_potatoes_annotations.csv') #copy the path of csv file 
df.head()

#calculate percent of two annotators will agree
agree = 0 
for i in range(len(df)):
  if df['annotator_1'][i] == df['annotator_2'][i]:
    agree += 1

#calculate disagreement observed 
do = 0 
for i in range(len(df)):
  if df['annotator_1'][i] != df['annotator_2'][i]:
    do += 1

#calculate disagreement by chance

pv1=0 #sum of first annotator thought the writer was with pro-vaccine
av1=0 #sum of first annotator thought the writer was with anti-vaccine
nv1=0 #sum of first annotator thought the writer was with neutral stance
xv1=0 #sum of first annotator thought the writer was with no stance
pv2=0 #sum of second annotator thought the writer was with pro_vaccine
av2=0 #sum of second annotator thought the writer was with anti_vaccine
nv2=0 #sum of second annotator thought the writer was with neutral_vaccine
xv2=0 #sum of second annotator thought the writer was with no stance

for i in range(len(df)):
  if df['annotator_1'][i] == '1':
    pv1 += 1
  elif df['annotator_1'][i] == '-1':
      av1 += 1
  elif df['annotator_1'][i] == '0':
      nv1 += 1
  elif df['annotator_1'][i] == 'X':
      xv1 += 1
  if df['annotator_2'][i] == '1':
    pv2 += 1
  elif df['annotator_1'][i] == '-1':
      av2 += 1
  elif df['annotator_1'][i] == '0':
      nv2 += 1
  elif df['annotator_1'][i] == 'X':
      xv2 += 1


#transform to percentage 
pv1=pv1/len(df)
av1=av1/len(df)
nv1=nv1/len(df)
xv1=xv1/len(df)
pv2=pv2/len(df)
av2=av2/len(df)
nv2=nv2/len(df)
xv2=xv2/len(df)

#calculate 
de = pv1*nv2 + pv1*av2 + pv1*xv2 + av1*pv2 + av1*nv2 + av1*xv2 + nv1*pv2 + nv1*av2 + nv1*xv2 + xv1*pv2 + xv1*av2 + xv1*nv2

alpha = 1 - do/len(df) / de 

print('{}\t{}'.format(agree/len(df),alpha))